Repository Echo-Chat-Systems/docs, pull requests merged in 2025-07, with the labels that each got.

#2 Ball'in work
  package-lock.json
  package.json
  src/components/Schema.js
  src/components/styles.schema.css
  src/css/custom.css
  src/theme/CodeBlock/Buttons/Button/index.js
  src/theme/CodeBlock/Buttons/CopyButton/index.js
  src/theme/CodeBlock/Buttons/CopyButton/styles.module.css
  src/theme/CodeBlock/Buttons/WordWrapButton/index.js
  src/theme/CodeBlock/Buttons/WordWrapButton/styles.module.css
  src/theme/CodeBlock/Buttons/index.js
  src/theme/CodeBlock/Buttons/styles.module.css
  src/theme/CodeBlock/Container/index.js
  src/theme/CodeBlock/Container/styles.module.css
  src/theme/CodeBlock/Content/Element.js
  src/theme/CodeBlock/Content/String.js
  src/theme/CodeBlock/Content/index.js
  src/theme/CodeBlock/Content/styles.module.css
  src/theme/CodeBlock/Layout/index.js
  src/theme/CodeBlock/Layout/styles.module.css
  src/theme/CodeBlock/Line/Token/index.js
  src/theme/CodeBlock/Line/index.js
  src/theme/CodeBlock/Line/styles.module.css
  src/theme/CodeBlock/Title/index.js
  src/theme/CodeBlock/index.js
Labels: documentation, enhancement

#3 Merge latest dev changes
  Todo.md
  docs/protocol/targets/admin/_category_.json
  docs/protocol/targets/auth/_category_.json
  docs/protocol/targets/auth/signout.mdx
  docs/protocol/targets/channels/_category_.json
  docs/protocol/targets/generic/error.mdx
  docs/protocol/targets/guilds/create.mdx
  docs/protocol/targets/invites/_category_.json
  docs/protocol/targets/messages/_category_.json
  docs/protocol/targets/postie/_category_.json
  docs/protocol/targets/social/_category_.json
  docs/protocol/targets/users/_category_.json
  docs/protocol/targets/users/get-self.mdx
  docs/protocol/targets/users/get.mdx
  docs/protocol/targets/users/rep-add.mdx
  docs/protocol/targets/users/rep-del.mdx
  docs/protocol/targets/users/rep-query.mdx
  docs/protocol/targets/users/update.mdx
  src/components/Authenticated.js
  src/components/styles.authenticated.css
  src/css/custom.css
Labels: documentation, enhancement

#4 Merge `guilds` work into main branch
  Todo.md
  docs/protocol/definitions/channel/data.mdx
  docs/protocol/definitions/guild/data.mdx
  docs/protocol/definitions/meta/permissions.mdx
  docs/protocol/targets/_template-page.mdx
  docs/protocol/targets/generic/error.mdx
  docs/protocol/targets/guilds/_list.mdx
  docs/protocol/targets/guilds/delete.mdx
  docs/protocol/targets/guilds/get.mdx
  docs/protocol/targets/guilds/placeholder.mdx
  docs/protocol/targets/guilds/update.mdx
  src/pages/index.module.css
Labels: documentation

#53 Completed `guilds`:`query` (#18)
  docs/protocol/targets/guilds/_list.mdx
  docs/protocol/targets/guilds/query.mdx
Labels: documentation, enhancement, targets-actions
